### ISSUE TITLE
Issue specifying initial state when doing reverse annealing

### ISSUE THREAD

**Issue by jli0108** [aws/amazon-braket-ocean-plugin-python#67]
**Describe the bug**
I am trying to do reverse annealing on the D-Wave Advantage_system6.1 machine, but I am having issues specifying the initial state. 
I am running everything on an Amazon Braket notebook instance.

According to the [D-Wave documentation](https://docs.dwavesys.com/docs/latest/c_solver_parameters.html#anneal-schedule), the `initial_state` parameter can be given as a list. If I do this, I get a `ValidationError`:
```
ValidationError: 1 validation error for DwaveAdvantageDeviceLevelParameters
initialState
  value is not a valid list (type=type_error.list)
```
I found that this issue has been brought up on D-Wave's community forum [here](https://support.dwavesys.com/hc/en-us/community/posts/4408011562647-Problem-using-reverse-annealing-through-AWS), where it is mentioned that on AWS the initial state is expected as a list rather than a dict. Simply changing it to a list gives me a `TypeError`, presumably because I have the qubits labeled by strings. No matter what I try though, it seems like I cannot avoid any errors. Apologies if this is user error, but I cannot find any working example of reverse annealing with a specified initial state on Braket.

**To reproduce**
```
import boto3
from braket.aws import AwsDevice
from braket.ocean_plugin import BraketSampler, BraketDWaveSampler
from dwave.system.composites import EmbeddingComposite, FixedEmbeddingComposite

# Enter the S3 bucket you created during onboarding in the code below
my_bucket = "amazon-braket-wugroup-us-east-1" # the name of the bucket
my_prefix = "folder_name" # the name of the folder in the bucket
s3_folder = (my_bucket, my_prefix)
client = boto3.client('s3')

# session and device
device_name = "arn:aws:braket:us-west-2::device/qpu/d-wave/Advantage_system6"
device = AwsDevice(device_name)
print('Device:', device)

qpu = BraketDWaveSampler(s3_folder,device_name)

# number of qubits
n = 4
h_dict = {str(i): -0.5 for i in range(n)}

J_dict = {}
for i in range(n-1):
        J_dict[str(i),str(i+1)] = 1
        
print("h:", h_dict)
print("J:", J_dict)

reverse_schedule = [[0.0, 1.0], [1, 0.25], [99, 0.25], [100, 1.0]]

#initial_state = {str(i): 1 for i in range(n)}
initial_state = [(i, 1) for i in range(n)]

print("initial state:", initial_state)

sampler = EmbeddingComposite(qpu)
response = sampler.sample_ising(h_dict, J_dict, 
                                num_reads=100,
                                annealing_time=1,
                                auto_scale=False,
                                return_embedding=True,
                                anneal_schedule=reverse_schedule,
                                initial_state=initial_state,
                                reinitialize_state=True)
```

**Expected behavior**
I expect a response with (possibly meaningful) samples, avoiding any error messages.

**System information**
A description of your system. Please provide:
- **Amazon Braket Python Ocean Plugin version**: 1.0.6
- **Amazon Braket Python SDK version**: 1.9.6.dev0
- **Amazon Braket Python Schemas version**: 1.4.1.dev0
- **Python version**: 3.7.11

**Comment by shpface** [comment]
Hi,
Thank you for bringing this issue to our attention. You are running into this issue because D-Wave's `EmbeddingComposite` is taking the list `initial_states` which the `BraketDWaveSampler` expects and is reformatting it to a dict. D-Wave recently published a function which will handle reformatting of `initial_states`. If we use this function in the Amazon Braket Ocean plugin, it would solve this issue and allow Braket to accept `initial_states` as dict. Would you be interested in contributing a pull request to solve this issue? I'm more than happy to assist if you have questions!

I think the changes we would need are,
* Add a dependency on `dwave-cloud-client>=0.9.4`
* Add a call to `dwave.cloud.solver.StructuredSolver.reformat_parameters()` defined [here](https://github.com/dwavesystems/dwave-cloud-client/blob/a1d4a9e76b007b5604428173277602549b443d2b/dwave/cloud/solver.py#L1072) from the `BraketDWaveSampler._process_solver_kwargs()` function [here](https://github.com/aws/amazon-braket-ocean-plugin-python/blob/bfb38402fa722e0486ae94b2185b9a2bc2dd8b4e/src/braket/ocean_plugin/braket_dwave_sampler.py#L303).
* Set a variable from the sampling methods in `BraketDWaveSampler` so that the variable type is available inside the `_process_solver_kwargs()` function

**Comment by jli0108** [comment]
Thanks so much for the assistance. I just made a pull request that fixes the issue.
